--- #YAML:1.0
name: ExtUtils-ParseXS
version: 2.09
author:
  - Maintained by Ken Williams, <ken@mathforum.org>
abstract: converts Perl XS code into C code
license: perl
requires:
  Config: 0
  Cwd: 0
  Exporter: 0
  File::Basename: 0
  File::Spec: 0
build_requires:
  ExtUtils::CBuilder: 0
provides:
  ExtUtils::ParseXS:
    file: lib/ExtUtils/ParseXS.pm
    version: 2.09
generated_by: Module::Build version 0.2608
