---
name: ExtUtils-ParseXS
version: 2.19_03
author:
  - 'Maintained by Ken Williams, <ken@mathforum.org>'
abstract: converts Perl XS code into C code
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  ExtUtils::CBuilder: 0
requires:
  Config: 0
  Cwd: 0
  Exporter: 0
  File::Basename: 0
  File::Spec: 0
configure_requires:
  Module::Build: 0.3305
provides:
  ExtUtils::ParseXS:
    file: lib/ExtUtils/ParseXS.pm
    version: 2.19_03
generated_by: Module::Build version 0.3305
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
