--- #YAML:1.0
name:               ExtUtils-ParseXS
version:            3.11
abstract:           converts Perl XS code into C code
author:
    - Ken Williams <ken@mathforum.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                0
    Cwd:                 0
    DynaLoader:          0
    Exporter:            0
    ExtUtils::CBuilder:  0
    File::Basename:      0
    File::Spec:          0
    Symbol:              0
    Test::More:          0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
