# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ExtUtils-ParseXS
version:      2.06
version_from: lib/ExtUtils/ParseXS.pm
installdirs:  perl
requires:
    Config:                        0
    Cwd:                           0
    Exporter:                      0
    File::Basename:                0
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
